### ISSUE TITLE
Usage of this

### ISSUE THREAD

**Issue by RealistikDash** [barrack-obama/Hangman#2]
Within your class, you utilise `this` as a reference to the current class. That is illegal. In this beautiful language, we utilise `self` as the name of the arg, and you specifically decided to introduce JavaScript balderdash upon this language. Shame on you.

**Comment by simonglob** [comment]
oh yeah lmao. too much java, i couldn't remember what it was, so i used this instead of self. but at the end of the day. jeg er ligeglad

**Comment by RealistikDash** [comment]
You cared enough to fix it. Good.
https://github.com/barrack-obama/Hangman/commit/9f04f1d15cb2bffc5e0774ded7ad37d3620a128e
